// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AgriHub.Models
{
    public partial class Broiler
    {
        public Broiler()
        {
            BroilerTrans = new HashSet<BroilerTrans>();
        }

        public int Id { get; set; }

        [Display(Name = "Batch No.")]
        [Required]
        [Column(TypeName = "VARCHAR(10)")]
        [StringLength(10)]
        public string BatchNo { get; set; }

        [Display(Name = "Chicks Day(s) Old")]
        [Required]
        public int ChicksDaysOld { get; set; }

        [Display(Name = "Date of Receipt")]
        public DateTime DateReceipt { get; set; }

        [Display(Name = "Qty Receipt")]
        [Required]
        public int QtyReceipt { get; set; }

        [Display(Name = "Qty On Hand")]
        [Required]
        public int QtyOnHand { get; set; }

        [Display(Name = "Brooder")]
        public string BrooderId { get; set; }

        [Display(Name = "Pin House")]
        public int PinHouseId { get; set; }
        public int PinCapacity { get; set; }
        
        [Column(TypeName = "decimal(18,2)")]
        public decimal? AvgWeight { get; set; }
        public DateTimeOffset TransactionDate { get; set; }
        public int CurrentWeek { get; set; }

        [Column(TypeName = "VARCHAR(30)")]
        public string LoggedBy { get; set; }

        public bool? BatchCompleted { get; set; }

        public DateTime? BatchCompletedOn { get; set; }

        [Column(TypeName = "VARCHAR(30)")]
        public string BatchCompletedBy { get; set; }

        public virtual Brooder Brooder { get; set; }
        public virtual PenHouse PinHouse { get; set; }
        public virtual ICollection<BroilerTrans> BroilerTrans { get; set; }
    }
}