// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AgriHub.Models
{
    public partial class BroilerTrans
    {
        public int Id { get; set; }
        public int BroilerId { get; set; }
        
        [StringLength(10)]
        [Column(TypeName = "VARCHAR(10)")]
        public string BatchNo { get; set; }
        public DateTimeOffset TransactionDate { get; set; }
        public int TransactionWeek { get; set; }
        public int TransactionDay { get; set; }
        public int OpeningStock { get; set; }
        public int? Mortality { get; set; }
        public int? ClosingStock { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? AvgWeight { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? StdWeight { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? FeedCons { get; set; }

        [StringLength(500)]
        [Column(TypeName = "VARCHAR(500)")]
        public string Comment { get; set; }

        [StringLength(30)]
        [Column(TypeName = "VARCHAR(30)")]
        public string LoggedBy { get; set; }

        public virtual Broiler BatchNoNavigation { get; set; }
    }
}