// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AgriHub.Models
{
    public partial class Brooder
    {
        public Brooder()
        {
            Broiler = new HashSet<Broiler>();
        }
        public string Id { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<Broiler> Broiler { get; set; }
    }
}