// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AgriHub.Models
{
    public partial class LayerTrans
    {
        public int Id { get; set; }
        public string BatchNo { get; set; }
        public DateTimeOffset? TransactionDate { get; set; }
        public int? TransactionWeek { get; set; }
        public int? OpeningStock { get; set; }
        public int? Mortality { get; set; }
        public int? ClosingStock { get; set; }
        public int? EggsCollected { get; set; }
        public int? EggSize { get; set; }
        public decimal? FeedCons { get; set; }
        public string Comment { get; set; }
        public string LoggedBy { get; set; }

        public virtual Layer BatchNoNavigation { get; set; }
        public virtual EggsSize EggSizeNavigation { get; set; }
    }
}