// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AgriHub.Models
{
    public partial class Layer
    {
        public Layer()
        {
            LayerTrans = new HashSet<LayerTrans>();
        }

        public string BatchNo { get; set; }
        public int ChicksDaysOld { get; set; }
        public int HouseId { get; set; }
        public int QtyReceipt { get; set; }
        public DateTime DateReceipt { get; set; }
        public int CurrentWeek { get; set; }
        public int? NoOfEggs { get; set; }
        public DateTimeOffset TransactionDate { get; set; }
        public string LoggedBy { get; set; }
        public bool? BatchCompleted { get; set; }
        public DateTime? BatchCompletedOn { get; set; }
        public string BatchCompletedBy { get; set; }

        public virtual LayerHouse House { get; set; }
        public virtual ICollection<LayerTrans> LayerTrans { get; set; }
    }
}