// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AgriHub.Models
{
    public partial class PenHouse
    {
        public PenHouse()
        {
            Broiler = new HashSet<Broiler>();
        }

        public int Id { get; set; }
        public int Capacity { get; set; }
        public bool Status { get; set; }

        public virtual ICollection<Broiler> Broiler { get; set; }
    }
}