// <auto-generated />
using System;
using AgriHub.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgriHub.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200811193431_sp_addbroiler_transaction")]
    partial class sp_addbroiler_transaction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgriHub.Models.Broiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AvgWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("BatchCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("BatchCompletedBy")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<DateTime?>("BatchCompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasMaxLength(10);

                    b.Property<string>("BrooderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ChicksDaysOld")
                        .HasColumnType("int");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateReceipt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoggedBy")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("PinCapacity")
                        .HasColumnType("int");

                    b.Property<int>("PinHouseId")
                        .HasColumnType("int");

                    b.Property<int>("QtyReceipt")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BrooderId");

                    b.HasIndex("PinHouseId");

                    b.ToTable("Broilers");
                });

            modelBuilder.Entity("AgriHub.Models.BroilerTrans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AvgWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNo")
                        .HasColumnType("VARCHAR(10)")
                        .HasMaxLength(10);

                    b.Property<int>("BroilerId")
                        .HasColumnType("int");

                    b.Property<int?>("ClosingStock")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("VARCHAR(500)")
                        .HasMaxLength(500);

                    b.Property<decimal?>("FeedCons")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoggedBy")
                        .HasColumnType("VARCHAR(30)")
                        .HasMaxLength(30);

                    b.Property<int?>("Mortality")
                        .HasColumnType("int");

                    b.Property<int>("OpeningStock")
                        .HasColumnType("int");

                    b.Property<decimal?>("StdWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransactionDay")
                        .HasColumnType("int");

                    b.Property<int>("TransactionWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BroilerId");

                    b.ToTable("BroilerTrans");
                });

            modelBuilder.Entity("AgriHub.Models.Brooder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brooders");
                });

            modelBuilder.Entity("AgriHub.Models.PenHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PenHouses");
                });

            modelBuilder.Entity("AgriHub.Models.Broiler", b =>
                {
                    b.HasOne("AgriHub.Models.Brooder", "Brooder")
                        .WithMany("Broiler")
                        .HasForeignKey("BrooderId");

                    b.HasOne("AgriHub.Models.PenHouse", "PinHouse")
                        .WithMany("Broiler")
                        .HasForeignKey("PinHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgriHub.Models.BroilerTrans", b =>
                {
                    b.HasOne("AgriHub.Models.Broiler", "BatchNoNavigation")
                        .WithMany("BroilerTrans")
                        .HasForeignKey("BroilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
